Class {
	#name : 'SmallDocMethodCommentEncoder',
	#superclass : 'SmallDocCommentEncoder',
	#category : 'SmallDoc',
	#package : 'SmallDoc'
}

{ #category : 'visiting main API' }
SmallDocMethodCommentEncoder >> visit: aMicElement [

	self shouldBeImplemented
]

{ #category : 'visiting' }
SmallDocMethodCommentEncoder >> visitAgenda: anAgenda [

	self shouldBeImplemented
]

{ #category : 'visiting' }
SmallDocMethodCommentEncoder >> visitAnchor: anAnchor [

	self shouldBeImplemented
]

{ #category : 'visiting - inline elements' }
SmallDocMethodCommentEncoder >> visitAnchorReference: anAnchorReference [

	self shouldBeImplemented
]

{ #category : 'visiting' }
SmallDocMethodCommentEncoder >> visitAnnotated: anAnnotated [

	self shouldBeImplemented
]

{ #category : 'visiting - inline elements' }
SmallDocMethodCommentEncoder >> visitAnnotation: anAnnotation [

	self shouldBeImplemented
]

{ #category : 'visiting' }
SmallDocMethodCommentEncoder >> visitBreak: aBreak [

	self shouldBeImplemented
]

{ #category : 'visiting - extensions' }
SmallDocMethodCommentEncoder >> visitCitation: aVisitor [

	self shouldBeImplemented
]

{ #category : 'visiting' }
SmallDocMethodCommentEncoder >> visitCode: aCodeBlock [

	self shouldBeImplemented
]

{ #category : 'visiting' }
SmallDocMethodCommentEncoder >> visitColumn: aColumn [

	self shouldBeImplemented
]

{ #category : 'visiting' }
SmallDocMethodCommentEncoder >> visitColumns: aColumns [

	self shouldBeImplemented
]

{ #category : 'visiting' }
SmallDocMethodCommentEncoder >> visitComment: aComment [

	self shouldBeImplemented
]

{ #category : 'visiting' }
SmallDocMethodCommentEncoder >> visitDay: aDay [

	self shouldBeImplemented
]

{ #category : 'visiting' }
SmallDocMethodCommentEncoder >> visitEnvironment: anEnvironment [

	self shouldBeImplemented
]

{ #category : 'visiting - inline elements' }
SmallDocMethodCommentEncoder >> visitFigure: aFigure [

	self shouldBeImplemented
]

{ #category : 'visiting' }
SmallDocMethodCommentEncoder >> visitFootnote: aFootnote [

	self shouldBeImplemented
]

{ #category : 'visiting' }
SmallDocMethodCommentEncoder >> visitHeader: aHeader [

	self shouldBeImplemented
]

{ #category : 'visiting' }
SmallDocMethodCommentEncoder >> visitHorizontalLine: anHorizontalLineBlock [

	self shouldBeImplemented
]

{ #category : 'visiting' }
SmallDocMethodCommentEncoder >> visitInputFile: anInputfile [

	self shouldBeImplemented
]

{ #category : 'visiting - inline elements' }
SmallDocMethodCommentEncoder >> visitItalic: aFormat [

	self shouldBeImplemented
]

{ #category : 'visiting - inline elements' }
SmallDocMethodCommentEncoder >> visitLink: aLink [

	self shouldBeImplemented
]

{ #category : 'visiting - list' }
SmallDocMethodCommentEncoder >> visitListItem: anItem [

	self shouldBeImplemented
]

{ #category : 'visiting' }
SmallDocMethodCommentEncoder >> visitMath: aMicMath [

	self shouldBeImplemented
]

{ #category : 'visiting - inline elements' }
SmallDocMethodCommentEncoder >> visitMathInline: aMicMathInline [

	self shouldBeImplemented
]

{ #category : 'visiting' }
SmallDocMethodCommentEncoder >> visitMetaData: aMetaData [

	self shouldBeImplemented
]

{ #category : 'visiting - inline elements' }
SmallDocMethodCommentEncoder >> visitMonospace: aFormat [

	self shouldBeImplemented
]

{ #category : 'visiting - list' }
SmallDocMethodCommentEncoder >> visitOrderedList: anOrderedList [

	self shouldBeImplemented
]

{ #category : 'visiting - list' }
SmallDocMethodCommentEncoder >> visitOrderedListItem: anItem [

	self shouldBeImplemented
]

{ #category : 'visiting - extensions' }
SmallDocMethodCommentEncoder >> visitPharoEvaluator: aScriptBlock [

	self shouldBeImplemented
]

{ #category : 'visiting - extensions' }
SmallDocMethodCommentEncoder >> visitPharoScript: aPharoScriptNode [

	self shouldBeImplemented
]

{ #category : 'visiting' }
SmallDocMethodCommentEncoder >> visitQuote: aQuote [

	self shouldBeImplemented
]

{ #category : 'visiting - inline elements' }
SmallDocMethodCommentEncoder >> visitRaw: aRawFormat [

	self shouldBeImplemented
]

{ #category : 'visiting - extensions' }
SmallDocMethodCommentEncoder >> visitScript: aSlide [

	self shouldBeImplemented
]

{ #category : 'visiting' }
SmallDocMethodCommentEncoder >> visitSegment: aSegment [

	self shouldBeImplemented
]

{ #category : 'visiting - extensions' }
SmallDocMethodCommentEncoder >> visitSlide: aSlide [

	self shouldBeImplemented
]

{ #category : 'visiting - inline elements' }
SmallDocMethodCommentEncoder >> visitStrike: aFormat [

	self shouldBeImplemented
]

{ #category : 'visiting' }
SmallDocMethodCommentEncoder >> visitTable: aTable [

	self shouldBeImplemented
]

{ #category : 'visiting' }
SmallDocMethodCommentEncoder >> visitTalk: aTalk [

	self shouldBeImplemented
]

{ #category : 'visiting - list' }
SmallDocMethodCommentEncoder >> visitUnorderedList: anUnorderedList [

	self shouldBeImplemented
]

{ #category : 'visiting - list' }
SmallDocMethodCommentEncoder >> visitUnorderedListItem: anUnorderedList [

	self shouldBeImplemented
]
